### ISSUE TITLE
 [dvf markers as  Leaflet.markercluster's cluster] : Uncaught Error: Invalid LatLng object: (NaN, NaN)

### ISSUE THREAD

**Issue by ghost** [humangeo/leaflet-dvf#114]
I'm trying to use the new markers (especially "PieChartMarker") provided with DFV as the "markerClusterGroup", and I'm getting this error: 
```
leaflet.js:5 Uncaught Error: Invalid LatLng object: (NaN, NaN)
    at o.LatLng (leaflet.js:5)
    at e._recalculateBounds (leaflet.markercluster.js:6)
```
Is there something I can do to make it work ?
Thanks for your help!

**Comment by sfairgrieve** [comment]
@lyDevops can you provide a little more info. as to your current setup?  It could definitely be something with `PieChartMarker`, but it's hard to say offhand without a little more info.

**Comment by tmeedend** [comment]
Hi, I am a colleague of @lyDevops .

This problem happens when we add a PieChartMarker to a « L.markerClusterGroup ». This group is from the leaflet MarkerCluster plugin : https://github.com/Leaflet/Leaflet.markercluster

If we add our PieChartMarker to a classic L.featureGroup, this problem doesn't occur.

We are using leaflet-1.0.3, markercluster-1.0.3 and leaflet-dvf-0.3.1.

Thank you again.

**Comment by tmeedend** [comment]
Hello, 

We can close this issue, the problem was that we were doing some divisions with zero.

Sorry for the inconvenience.

**Comment by sfairgrieve** [comment]
@tmeedend Great!  Thanks for the heads up.
