### ISSUE TITLE
Use different markers in GeohashDataLayer

### ISSUE THREAD

**Issue by ikirmitz** [humangeo/leaflet-dvf#57]
Hi there,

following the Geohashes example I've built a map that feeds directly from a JSON output from SOLR. The underlying data is encoded in Geohashes. Everything works fine but I want to change the markers from rectangles to L.MapMarker. I know you can bypass the default markers using getMarker but I couldn't find any clear documentation on how to do that. 
Can you please provide an example if possible?

Many thanks,

Ioannis

**Comment by sfairgrieve** [comment]
Ioannis,

GeohashDataLayer is just a convenience class for displaying rectangles instead of markers - it just sets some of the data layer options for you and overrides some of the base DataLayer code to return rectangles.  There are a couple of ways to accomplish what you need.  You can use the _getMarker_ option with _L.DataLayer_, or the _L.MapMarkerDataLayer_.  Here are examples of both:

L.MapMarkerDataLayer
```javascript
var geohashLayer = new L.MapMarkerDataLayer(data, {
     locationMode: L.LocationModes.GEOHASH,
     geohashField: <reference to geohash property>,
     ...
});
```

L.DataLayer
```javascript
var geohashLayer = new L.DataLayer(data, {
     locationMode: L.LocationModes.GEOHASH,
     geohashField: <reference to geohash property>,
     getMarker: function (latLng, layerOptions, record) {
         return new L.MapMarker(latLng, layerOptions);
     },
     ...
});
```

**Comment by ikirmitz** [comment]
Excellent, 
thank you very much!
